# @see https://devdocs.prestashop.com/1.7/modules/concepts/controllers/admin-controllers/#how-to-map-an-action-of-your-controller-to-a-uria# @see https://devdocs.prestashop.com/1.7/modules/concepts/controllers/admin-controllers/#how-to-map-an-action-of-your-controller-to-a-uri
ds_dsgprdcookie_cookie_index:
    path: /demo-doctrine/quotes
    methods: [GET]
    defaults:
        _controller: 'Module\DemoDoctrine\Controller\Admin\QuotesController::indexAction'
        _legacy_controller: 'AdminDemodoctrineQuote'
        _legacy_link: 'AdminDemodoctrineQuote'

ds_dsgprdcookie_cookie_search:
    path: /demo-doctrine/quotes
    methods: [POST]
    defaults:
        _controller: 'Module\DemoDoctrine\Controller\Admin\QuotesController::searchAction'
        _legacy_controller: 'AdminDemodoctrineQuote'
        _legacy_link: 'AdminDemodoctrineQuote:search'

ds_dsgprdcookie_cookie_generate:
    path: /demo-doctrine/generate
    methods: [GET, POST]
    defaults:
        _controller: 'Module\DemoDoctrine\Controller\Admin\QuotesController::generateAction'
        _legacy_controller: 'AdminDemodoctrineQuote'
        _legacy_link: 'AdminDemodoctrineQuote:generate'

ds_dsgprdcookie_cookie_create:
    path: /demo-doctrine/quotes/new
    methods: [GET, POST]
    defaults:
        _controller: 'Module\DemoDoctrine\Controller\Admin\QuotesController::createAction'
        _legacy_controller: 'AdminDemodoctrineQuote'
        _legacy_link: 'AdminDemodoctrineQuote:add'

ds_dsgprdcookie_cookie_edit:
    path: /demo-doctrine/quotes/{quoteId}/edit
    methods: [GET, POST]
    defaults:
        _controller: 'Module\DemoDoctrine\Controller\Admin\QuotesController::editAction'
        _legacy_controller: 'AdminDemodoctrineQuote'
        _legacy_link: 'AdminDemodoctrineQuote:edit'
    requirements:
        quoteId: \d+

ds_dsgprdcookie_cookie_delete:
    path: /demo-doctrine/quotes/{quoteId}/delete
    methods: [DELETE]
    defaults:
        _controller: 'Module\DemoDoctrine\Controller\Admin\QuotesController::deleteAction'
        _legacy_controller: 'AdminDemodoctrineQuote'
        _legacy_link: 'AdminDemodoctrineQuote:deletequote'
    requirements:
        quoteId: \d+

ds_dsgprdcookie_cookie_bulk_delete:
    path: /demo-doctrine/quotes/bulkDelete
    methods: [POST]
    defaults:
        _controller: 'Module\DemoDoctrine\Controller\Admin\QuotesController::deleteBulkAction'
        _legacy_controller: 'AdminDemodoctrineQuote'
        _legacy_link: 'AdminDemodoctrineQuote:submitBulkdeletequote'
