# @see https://devdocs.prestashop.com/1.7/modules/concepts/controllers/admin-controllers/#how-to-map-an-action-of-your-controller-to-a-uria# @see https://devdocs.prestashop.com/1.7/modules/concepts/controllers/admin-controllers/#how-to-map-an-action-of-your-controller-to-a-uri
ds_gprdcookie_cookie_index:
    path: /dsgprdcookie/cookies
    methods: GET|POST
    controller: 'DarkSide\DsGprdCookie\Controller\Admin\CookieController::indexAction'

ds_gprdcookie_cookie_field_index:
  path: /dsgprdcookie/cookie/field
  methods: [GET]
  defaults:
      _controller: 'DarkSide\DsGprdCookie\Controller\Admin\CookieFieldController::indexAction'
      _legacy_controller: 'AdminDsGprdCookieField'
      _legacy_link: 'AdminDsGprdCookieField'

ds_gprdcookie_cookie_search:
    path: /dsgprdcookie/cookies
    methods: [POST]
    defaults:
        _controller: 'DarkSide\DsGprdCookie\Controller\Admin\CookieController::searchAction'
        _legacy_controller: 'AdminDsGprdCookie'
        _legacy_link: 'AdminDsGprdCookie:search'

ds_gprdcookie_cookie_field_search:
    path: /dsgprdcookie/cookie/field
    methods: [POST]
    defaults:
        _controller: 'DarkSide\DsGprdCookie\Controller\Admin\CookieFieldController::searchAction'
        _legacy_controller: 'AdminDsGprdCookieField'
        _legacy_link: 'AdminDsGprdCookieField:search'

ds_gprdcookie_cookie_create:
    path: /dsgprdcookie/cookies/new
    methods: [GET, POST]
    controller: 'DarkSide\DsGprdCookie\Controller\Admin\CookieController::createAction'

ds_gprdcookie_cookie_edit:
    path: /dsgprdcookie/cookies/{id}/edit
    methods: [GET, POST]
    defaults:
        _controller: 'DarkSide\DsGprdCookie\Controller\Admin\CookieController::editAction'
        _legacy_controller: 'AdminDsGprdCookie'
        _legacy_link: 'AdminDsGprdCookie:edit'
    requirements:
        id: \d+

ds_gprdcookie_cookie_delete:
    path: /dsgprdcookie/cookies/{id}/delete
    methods: [POST]
    defaults:
        _controller: 'DarkSide\DsGprdCookie\Controller\Admin\CookieController::deleteAction'
        _legacy_controller: 'AdminDsGprdCookie'
        _legacy_link: 'AdminDsGprdCookie:delete'
    requirements:
        id: \d+

ds_gprdcookie_cookie_field_edit:
    path: /dsgprdcookie/cookie/field/{id}/edit
    methods: [GET, POST]
    defaults:
        _controller: 'DarkSide\DsGprdCookie\Controller\Admin\CookieFieldController::editAction'
        _legacy_controller: 'AdminDsGprdCookieField'
        _legacy_link: 'AdminDsGprdCookieField:edit'
    requirements:
        id: \d+

ds_gprdcookie_cookie_bulk_delete:
    path: /dsgprdcookie/cookies/bulkDelete
    methods: [POST]
    defaults:
        _controller: 'DarkSide\DsGprdCookie\Controller\Admin\CookieController::deleteBulkAction'

ds_gprdcookie_cookie_build:
    path: /dsgprdcookie/cookie/build
    methods: [GET]
    defaults:
        _controller: 'DarkSide\DsGprdCookie\Controller\Admin\CookieController:buildAction'
        _legacy_controller: 'AdminDsGprdCookie'
        _legacy_link: 'AdminDsGprdCookie:build'