imports:
    - { resource: ./common.yml }

services:
    # Form services
    darkside.module.dsgprd.type.quote:
        class: 'DarkSide\DsGPRDCookie\Form\CookieType'
        parent: 'form.type.translatable.aware'
        public: true
        arguments:
            - '@=service("prestashop.adapter.multistore_feature").isUsed()'
        tags:
            - { name: form.type }

    darkside.module.dsgprd.form.identifiable_object.data_provider.cookie_form_data_provider:
        class: 'DarkSide\DsGPRDCookie\Form\CookieFormDataProvider'
        arguments:
            - '@darkside.module.dsgprd.repository.cookie_repository'

    darkside.module.dsgprd.form.identifiable_object.builder.cookie_form_builder:
        class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Builder\FormBuilder'
        public: true
        factory: 'prestashop.core.form.builder.form_builder_factory:create'
        arguments:
            - 'DarkSide\DsGPRDCookie\Form\CookieType'
            - '@darkside.module.dsgprd.form.identifiable_object.data_provider.cookie_form_data_provider'

    darkside.module.dsgprd.form.identifiable_object.data_handler.cookie_form_data_handler:
        class: 'DarkSide\DsGPRDCookie\Form\CookieFormDataHandler'
        arguments:
            - '@darkside.module.dsgprd.repository.cookie_repository'
            - '@prestashop.core.admin.lang.repository'
            - '@doctrine.orm.default_entity_manager'

    darkside.module.dsgprd.form.identifiable_object.handler.cookie_form_handler:
        class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Handler\FormHandler'
        public: true
        factory: 'prestashop.core.form.identifiable_object.handler.form_handler_factory:create'
        arguments:
            - '@darkside.module.dsgprd.form.identifiable_object.data_handler.cookie_form_data_handler'

    # Grid services
    darkside.module.dsgprd.grid.definition.factory.cookies:
        class: 'DarkSide\DsGPRDCookie\Grid\Definition\Factory\CookieGridDefinitionFactory'
        parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'

    darkside.module.dsgprd.grid.query_builder.quote:
        class: 'DarkSide\DsGPRDCookie\Grid\Query\CookieQueryBuilder'
        parent: 'prestashop.core.grid.abstract_query_builder'
        public: true
        arguments:
            - '@prestashop.core.query.doctrine_search_criteria_applicator'
            - "@=service('prestashop.adapter.legacy.context').getContext().language.id"

    darkside.module.dsgprd.grid.data_provider.cookies:
        class: '%prestashop.core.grid.data.factory.doctrine_grid_data_factory%'
        arguments:
            - '@darkside.module.dsgprd.grid.query_builder.quote'
            - '@prestashop.core.hook.dispatcher'
            - '@prestashop.core.grid.query.doctrine_query_parser'
            - 'quote'

    darkside.module.dsgprd.grid.factory.cookies:
        class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
        public: true
        arguments:
            - '@darkside.module.dsgprd.grid.definition.factory.cookies'
            - '@darkside.module.dsgprd.grid.data_provider.cookies'
            - '@prestashop.core.grid.filter.form_factory'
            - '@prestashop.core.hook.dispatcher'
